[build]
base = "."
command = "npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
DATABASE_URL = "postgresql://neondb_owner:npg_4QE1vOrmTyjF@ep-muddy-credit-ae6zy7i3-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require"
SESSION_SECRET = "your-secret-key-here-change-in-production"
NODE_ENV = "development"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
